export const DummyData = [
  {
    products: [
      {
        name: "Bull dogs",
        category: "dogs",
        price: 3.89,
        currency: "USD",
        image: {
          src: "https://images.pexels.com/photos/850602/pexels-photo-850602.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
          alt: "dogs-img",
        },
        bestseller: true,
        featured: false,
        details: null,
      },
      {
        name: "Egg Balloon",
        category: "food",
        price: 93.89,
        currency: "USD",
        image: {
          alt: "",
          src: "https://images.pexels.com/photos/35638/labrador-breed-dogs-animal.jpg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        name: "Dog with kids",
        category: "animal",
        price: 100,
        currency: "USD",
        image: {
          src: "https://images.pexels.com/photos/3198049/pexels-photo-3198049.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
          alt: "dog",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        name: "Dog with kids",
        category: "animal",
        price: 100,
        currency: "USD",
        image: {
          src: "https://images.pexels.com/photos/3198049/pexels-photo-3198049.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
          alt: "dog",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        name: "Dog with kids",
        category: "animal",
        price: 100,
        currency: "USD",
        image: {
          src: "https://images.pexels.com/photos/3198049/pexels-photo-3198049.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
          alt: "dog",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        name: "Dog with kids",
        category: "animal",
        price: 100,
        currency: "USD",
        image: {
          src: "https://images.pexels.com/photos/257540/pexels-photo-257540.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
          alt: "dog",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        name: "Dog with kids",
        category: "animal",
        price: 100,
        currency: "USD",
        image: {
          src: "https://images.pexels.com/photos/604681/pexels-photo-604681.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
          alt: "dog",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        name: "lonely Dog",
        category: "animal",
        price: 100,
        currency: "USD",
        image: {
          src: "https://images.pexels.com/photos/9660872/pexels-photo-9660872.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
          alt: "dog",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        name: "Architecture",
        category: "landmarks",
        price: 101,
        currency: "USD",
        dimmentions: {
          width: 1020,
          height: 1020,
        },
        image: "",
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        name: "Samurai King Restling",
        category: "landmarks",
        price: 101,
        currency: "USD",
        image: {
          src: "",
          alt: "",
        },
        bestseller: false,
        featured: true,
        details: {
          dimmentions: {
            width: 1020,
            height: 1020,
          },
          size: 15000,
          description:
            "So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely",
        },
      },
    ],
  },
];
