export const Products = [
  {
    name: "Bull dogs",
    category: "pets",
    id: 1,
    price: 3.89,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/ydemmpmz",
      alt: "dogs-img",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    name: "Egg Balloon",
    category: "food",
    price: 93.89,
    currency: "USD",
    id: 2,
    image: {
      alt: "",
      src: "https://tinyurl.com/rd27ptsb",
    },
    bestseller: false,
    featured: true,
    details: null,
  },
  {
    name: "Dog",
    id: 3,
    category: "pets",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/28rp73j5",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    id: 4,
    category: "animal",
    price: 102,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/3hrhz9ke",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    id: 5,
    category: "pets",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/bp9pspe5",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    id: 6,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/3b5a3uzy",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog with kids",
    id: 7,
    category: "animal",
    price: 200,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/73y82nnk",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog with kids",
    id: 8,
    category: "animal",
    price: 400,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/4zsndu5t",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog with kids",
    id: 9,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/ekk46uh3",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog with kids",
    id: 10,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/r25zc4ts",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog kids",
    id: 11,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/y6ds8z6r",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog with kids",
    id: 12,
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/xud4nv2w",
      alt: "dog",
    },
    bestseller: false,
    featured: true,
    details: null,
  },
  {
    name: "Dog with kids",
    id: 13,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/43bwjh3h",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "lonely Dog",
    id: 14,
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/5apufyv9",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "lone Dog",
    id: 15,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/ckeyfkps",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Architecture",
    id: 16,
    category: "landmarks",
    price: 101,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://tinyurl.com/ysnwwuse",
      alt: "img",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Samurai King Restling",
    id: 17,
    category: "landmarks",
    price: 101,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/42w6exva",
      alt: "",
    },
    bestseller: false,
    featured: true,
    details: {
      dimmentions: {
        width: 1020,
        height: 1020,
      },
      size: 15000,
      description:
        "So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely",
    },
  },
  {
    name: "Samurai King Restling",
    id: 18,
    category: "landmarks",
    price: 101,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/n6s3wuac",
      alt: "",
    },
    bestseller: false,
    featured: true,
    details: {
      dimmentions: {
        width: 1020,
        height: 1020,
      },
      size: 15000,
      description:
        "So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely",
    },
  },
  {
    name: "Dog",
    id: 19,
    category: "nature",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/2jk3aktn",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    id: 20,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/2dv6wpef",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    id: 21,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/fnd466zf",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    id: 22,
    category: "nature",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/ccd2z8h5",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    id: 23,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://tinyurl.com/3pdju6yr",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    category: "animal",
    price: 105,
    currency: "USD",
    id: 24,
    image: {
      src: "https://tinyurl.com/3pdju6yr",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
];
