export const Products = [
  {
    name: "Bull dogs",
    category: "dogs",
    id: 1,
    price: 3.89,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/850602/pexels-photo-850602.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dogs-img",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    name: "Egg Balloon",
    category: "food",
    price: 93.89,
    currency: "USD",
    id: 2,
    image: {
      alt: "",
      src: "https://images.pexels.com/photos/35638/labrador-breed-dogs-animal.jpg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    },
    bestseller: false,
    featured: true,
    details: null,
  },
  {
    name: "Dog",
    id: 3,
    category: "pets",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/101635/pexels-photo-101635.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    id: 4,
    category: "animal",
    price: 102,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    id: 5,
    category: "pets",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/1851164/pexels-photo-1851164.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    id: 6,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/38008/pexels-photo-38008.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog with kids",
    id: 7,
    category: "animal",
    price: 200,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/733416/pexels-photo-733416.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog with kids",
    id: 8,
    category: "animal",
    price: 400,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/60050/huskies-husky-blue-eye-dog-60050.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog with kids",
    id: 9,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/3198049/pexels-photo-3198049.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog with kids",
    id: 10,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/4671145/pexels-photo-4671145.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog kids",
    id: 11,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/257540/pexels-photo-257540.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog with kids",
    id: 12,
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/9327035/pexels-photo-9327035.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: true,
    details: null,
  },
  {
    name: "Dog with kids",
    id: 13,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/604681/pexels-photo-604681.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "lonely Dog",
    id: 14,
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/9660872/pexels-photo-9660872.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "lone Dog",
    id: 15,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/33287/dog-viszla-close.jpg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Architecture",
    id: 16,
    category: "landmarks",
    price: 101,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/9327037/pexels-photo-9327037.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "img",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Samurai King Restling",
    id: 17,
    category: "landmarks",
    price: 101,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/4000092/pexels-photo-4000092.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "",
    },
    bestseller: false,
    featured: true,
    details: {
      dimmentions: {
        width: 1020,
        height: 1020,
      },
      size: 15000,
      description:
        "So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely",
    },
  },
  {
    name: "Samurai King Restling",
    id: 18,
    category: "landmarks",
    price: 101,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/4083443/pexels-photo-4083443.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "",
    },
    bestseller: false,
    featured: true,
    details: {
      dimmentions: {
        width: 1020,
        height: 1020,
      },
      size: 15000,
      description:
        "So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely",
    },
  },
  {
    name: "Dog",
    id: 19,
    category: "nature",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/8499234/pexels-photo-8499234.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    id: 20,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/4130054/pexels-photo-4130054.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    id: 21,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/6291572/pexels-photo-6291572.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    id: 22,
    category: "nature",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/8499859/pexels-photo-8499859.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    id: 23,
    category: "animal",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/6302310/pexels-photo-6302310.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Dog",
    category: "animal",
    price: 105,
    currency: "USD",
    id: 24,
    image: {
      src: "https://images.pexels.com/photos/6302310/pexels-photo-6302310.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      alt: "dog",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
];
